language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.cache/bower
  - $HOME/.gradle
  - $HOME/.npm
  - .gradle
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
env:
  - CXX=g++-6
